

/* Criando as tabelas */ 

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(60),
	IDADE VARCHAR(3),
	EMAIL VARCHAR(40),
	DATA_ADM DATE,
	IDCARGO INT,
	IDENDERECO INT,
	IDTELEFONE INT
)
GO

CREATE TABLE CARGO (
	IDCARGO INT PRIMARY KEY IDENTITY,
	NOMECARGO VARCHAR(30),
	SALARIO MONEY
)
GO

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY IDENTITY,
	ESTADO CHAR(2),
	BAIRRO VARCHAR(30),
	RUA VARCHAR(40),
	NUMERO VARCHAR(5)
)
GO


CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(20),
	TIPO CHAR(3)
)
GO

-- ATRIBUINDO AS FK--
ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_CARGO_FUNCIONARIO
FOREIGN KEY(IDCARGO)
REFERENCES CARGO(IDCARGO)
GO

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_ENDERECO_FUNCIONARIO
FOREIGN KEY(IDENDERECO)
REFERENCES ENDERECO(IDENDERECO)
GO

ALTER TABLE FUNCIONARIO
ADD CONSTRAINT FK_TELEFONE_FUNCIONARIO
FOREIGN KEY (IDTELEFONE)
REFERENCES TELEFONE(IDTELEFONE)
GO
