
CREATE DATABASE SIARECRUTER

USE SIARECRUTER

/* Criando as tabelas */ 

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(60),
	IDADE VARCHAR(3),
	EMAIL VARCHAR(40),
	DATA_ADM DATE
)
GO

CREATE TABLE CARGO (
	IDCARGO INT PRIMARY KEY IDENTITY,
	NOMECARGO VARCHAR(30),
	SALARIO MONEY
)
GO

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY IDENTITY,
	ESTADO CHAR(2),
	BAIRRO VARCHAR(30),
	RUA VARCHAR(40),
	NUMERO VARCHAR(5)
)
GO


CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY IDENTITY,
	NUMERO VARCHAR(20),
	TIPO CHAR(3)
)
GO
