/* SCRIPT DE CRIAÇÃO */

CREATE DATABASE LIVRARIA
GO

USE LIVRARIA 
GO

CREATE TABLE PESSOAS(
	ID_USUARIO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	TELEFONE VARCHAR(20),
	EMAIL VARCHAR (60)
)
GO

CREATE TABLE LIVROS (
	ID_LIVRO INT IDENTITY(1,1) PRIMARY KEY,
	TITULO VARCHAR(30),
	AUTOR VARCHAR(30),
	GENERO CHAR(1),
	ANO_PUBLICACAO DATE
)
GO


CREATE TABLE EMPRESTIMO(
	ID_EMPRESTIMO INT IDENTITY (1,1) PRIMARY KEY,
	ID_USUARIO INT,
	ID_LIVRO INT,
	DATA_EMPRESTIMO DATE,
	DATA_DEVOLUCAO DATE
)
GO

ALTER TABLE EMPRESTIMO
ADD CONSTRAINT FK_ID_USUARIO FOREIGN KEY (ID_USUARIO)
REFERENCES PESSOAS(ID_USUARIO)
GO


ALTER TABLE EMPRESTIMO 
ADD CONSTRAINT FK_ID_LIVRO FOREIGN KEY (ID_LIVRO)
REFERENCES LIVROS(ID_LIVRO)
GO

USE LIVRARIA 
GO

-- inserts pessoas
INSERT INTO PESSOAS VALUES ('DANIEL', '27998785211', 'DANIEL@GMAIL.COM')
GO

-- insert livros
INSERT INTO LIVROS VALUES ('A CABANA', 'YOUNG WILLIAM', 'SUSPENSE', '2007')
GO

-- insert emprestimos
INSERT INTO EMPRESTIMO VALUES (3,3, '2024-06-18', '2024-06-20')
GO



