/* REGRAS SOBRE FK A SEREM SEGUIDAS,
 - Em relacionamentos 1x1 a chave estrangeira fica na tabela mais fraca 
 - em relacionamento 1xN a chave estrangeira ficara sempre na cardinalidade N */

CREATE TABLE CLIENTE (
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF	VARCHAR(15) UNIQUE
);


CREATE TABLE ENDERECO( 
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
); 



CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);


-- INSERINDO DADOS NA TABELA CLIENTE
INSERT INTO CLIENTE VALUES(NULL, 'DANIEL', 'M', 'JOAO@IG.COM', '7656789254');
INSERT INTO CLIENTE VALUES(NULL, 'ISADORA', 'M', 'ISADORA@IG.COM', '987856365');
INSERT INTO CLIENTE VALUES(NULL, 'SOFIA', 'M', 'SOFIA@IG.COM', '158789887');


-- INSERINDO DADOS NA TABELA ENDEREÇO
INSERT INTO ENDERECO VALUES(NULL, 'SOLEMAR JACARAIPE', 'SERRA', 'PARQUE JACARAIPE', 'MG', 1);


-- INSERINDO DADOS NA TABELA TELEFONE
INSERT INTO TELEFONE VALUES( NULL, 'COM', '998257545', 3);
INSERT INTO TELEFONE VALUES( NULL, 'RES', '998257545', 3);
INSERT INTO TELEFONE VALUES( NULL, 'RES', '998257545', 1);


