/* Utilizando triggers  */ 
 
 CREATE TABLE USUARIO(
     IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(30), 
     SENHA VARCHAR(100)
  );
  
 /* toda vez que um usuario for apagado na tabela usuario fazer um backup automaticamente */
 
 DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USUARIO VALUES
	(NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
$
INSERT INTO USUARIO VALUES(NULL,'DANIEL','DAN777', '123456');

DELETE FROM USUARIO WHERE IDUSUARIO = 1;

delimiter ;
