/* Utilizando triggers  */ 
 
 CREATE TABLE USUARIO(
     IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
     NOME VARCHAR(30), 
     SENHA VARCHAR(100)
  );
  
 /* toda vez que um usuario for apagado na tabela usuario fazer um backup automaticamente */
 
 DELIMITER $

CREATE TRIGGER BACKUP_USER
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USUARIO VALUES
	(NULL,OLD.IDUSUARIO,OLD.NOME,OLD.LOGIN);
END
$
INSERT INTO USUARIO VALUES(NULL,'DANIEL','DAN777', '123456');

DELETE FROM USUARIO WHERE IDUSUARIO = 1;

delimiter ;



/*Comunicacao entre bancos */

CREATE DATABASE LOJA;
USE LOJA;
CREATE TABLE PRODUTO (
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL,1000,'TESTE',0.8);
SELECT * FROM BACKUP.BKP_PRODUTO;

/* QUANDO INSERIR UM PRODUTO EM UMA TABELA TAMBEM INSERIR NA OUTRA PARA POSSUIR
DUAS TABELAS SINCRONIZADAS*/
