CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(10) NOT NULL,
SEXO ENUM('M','F') NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
CPF VARCHAR(15)
);

CREATE TABLE ENDERECO(
IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
RUA VARCHAR(10) NOT NULL,
BAIRRO VARCHAR(10) NOT NULL,
CIDADE VARCHAR(10) NOT NULL,
ESTADO CHAR(2) NOT NULL
);

CREATE TABLE TELEFONE( 
IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
TIPO ENUM('RES', 'COM','CEL') NOT NULL,
NUMERO VARCHAR(10) NOT NULL
);

 
/* Chave estrangeira é a chave primária de uma tabela que vai em outra tabela
 fazer referencia  */
 
 /* EM RELACIONAMENTO 1X1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA
	EM RELACIONAMENTO 1XN FICARA SEMPRE NA FICARA NA CARDINALIDADE N
 */
