CREATE DATABASE CARTEIRA
GO

CREATE TABLE INVESTIMENTO(
	ID int primary key identity(1,1),
	PAPEL varchar(25),
	CATEGORIA varchar(40),
	PRECO_UNIDADE MONEY,
	QUANTIDADE int,
	INVESTIMENTO money,
	DATA_COMPRA date
)
GO

CREATE TABLE RENDIMENTOS(
	ID INT PRIMARY KEY IDENTITY(1,1),
	PAPEL VARCHAR(25),
	CATEGORIA VARCHAR(40),
	VALOR_RENDIDO MONEY,
	DATA_RENDIMENTO DATE
)
GO
