CREATE DATABASE ECOMMERCE
GO

USE ECOMMERCE
GO

CREATE TABLE JOGOS(
	ID_JOGO INT IDENTITY(1,1) PRIMARY KEY,
	JOGO_NOME VARCHAR(40),
	JOGO_GENERO VARCHAR(30),
	JOGO_PRECO MONEY,
	QTD_ESTOQUE INT
)
GO
-- CONSTRAINT PARA NÃO DEIXAR QUE UM JOGO DE MESMO NOME SEJA INSERIDO.	
ALTER TABLE JOGOS
ADD CONSTRAINT UNICO_JOGO UNIQUE(JOGO_NOME);
GO

	

CREATE TABLE CLIENTES(
	CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
	CLIENTE_LOGIN VARCHAR(30),
	CLIENTE_SENHA VARBINARY(128),
	CLIENTE_NOME VARCHAR(60),
	EMAIL VARCHAR(30),
	DATA_ANIVERSARIO DATE,
	SEXO CHAR(1),
	CONSTRAINT chk_sexo CHECK (SEXO IN ('M', 'F'))
)
GO


CREATE TABLE ENDERECO(
	ENDERECO_ID INT IDENTITY(1,1) PRIMARY KEY,
	ESTADO CHAR(2),
	CIDADE VARCHAR(20),
	RUA VARCHAR(30),
	NUMERO VARCHAR(10),
	CEP CHAR(8),
	CLIENTE_ID INT
)
GO
-- ADICIONANDO A FOREIGN KEY DO CLIENTE A TABELA ENDERECO 
ALTER TABLE ENDERECO
ADD CONSTRAINT FK_CLIENTE_ID
FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
GO


CREATE TABLE ORDEM(
	ORDEM_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORDEM_DATE DATE,
	QUANTIDADE INT,
	VALOR_TOTAL MONEY,
	CLIENTE_ID INT,
	ID_JOGO INT
)
GO

-- ADICIONANDO A FOREIGN KEY DO CLIENTE A TABELA ORDEM
ALTER TABLE ORDEM 
ADD CONSTRAINT FK_CLIENTE_ID_ORDEM
FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTES(CLIENTE_ID)
GO


-- ADICIONANDO A FOREIGN KEY DO JOGO A TABELA ORDEM
ALTER TABLE ORDEM
ADD CONSTRAINT FK_ID_JOGO_ORDEM
FOREIGN KEY(ID_JOGO) REFERENCES JOGOS(ID_JOGO)
GO

-- Criando trigger para quando uma ordem de compra for executada diminuir uma unidade em estoque do jogo.
CREATE TRIGGER atualizaEstoque
ON ORDEM 
AFTER INSERT 
AS
BEGIN
	DECLARE @ID_jogo INT;
	DECLARE @QUANTIDADE INT;
	-- OBTÉM OS VALORES INSERIDOS
	SELECT @ID_JOGO = ID_JOGO, @QUANTIDADE = QUANTIDADE 
	FROM INSERTED;

	--ATUALIZA A QUANTIDADE EM ESTOQUE DO JOGO
	UPDATE JOGOS 
	SET QTD_ESTOQUE = QTD_ESTOQUE - @QUANTIDADE
	WHERE ID_JOGO = @ID_JOGO;
END;
GO

CREATE TABLE PAGAMENTO(
	TRANSACAO_ID INT IDENTITY(1,1) PRIMARY KEY,
	FORMA_PAGAMENTO VARCHAR(30),
	DATA_PAGAMENTO DATE,
	ID_ORDEM INT
)
GO

-- ADICIONANDO FOREIGN KEY DA ORDEM A TABELA DE PAGAMENTO
ALTER TABLE PAGAMENTO
ADD CONSTRAINT FK_ORDEM_ID
FOREIGN KEY(ID_ORDEM) REFERENCES ORDEM(ORDEM_ID)
GO

CREATE TABLE AVALIACAO(
	AVALIACAO_ID INT IDENTITY(1,1) PRIMARY KEY,
	TEXTO_REVIEW VARCHAR(400),
	DATE_REVIEW DATE,
	ID_CLIENTE INT,
	ID_JOGO INT,
)
GO


CREATE TABLE AVALIACAO(
	AVALIACAO_ID INT IDENTITY(1,1) PRIMARY KEY,
	TEXTO_REVIEW VARCHAR(400),
	DATE_REVIEW DATE,
	ID_CLIENTE INT,
	ID_JOGO INT,
)
GO
-- ADICIONANDO FOREIGN KEY DO CLIENTE  A TABELA DE AVALIAACAO;
ALTER TABLE AVALIACAO
ADD CONSTRAINT FK_CLIENTE_ID_AVALIACAO
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(CLIENTE_ID)
GO

-- ADICIONANDO FOREIGN KEY DO JOGO  A TABELA DE AVALIAACAO;
ALTER TABLE AVALIACAO
ADD CONSTRAINT FK_JOGO_ID_AVALIACAO
FOREIGN KEY(ID_JOGO) REFERENCES JOGOS(ID_JOGO)
GO
