CREATE DATABASE ECOMMERCE
GO

USE ECOMMERCE
GO

CREATE TABLE JOGOS(
	ID_JOGO INT IDENTITY(1,1) PRIMARY KEY,
	JOGO_NOME VARCHAR(40),
	JOGO_GENERO VARCHAR(30),
	JOGO_PRECO MONEY,
	QTD_ESTOQUE INT
);
GO

CREATE TABLE ENDERECO(
	ENDERECO_ID INT IDENTITY(1,1) PRIMARY KEY,
	ESTADO CHAR(1),
	CIDADE VARCHAR(20),
	RUA VARCHAR(30),
	NUMERO VARCHAR(10),
	CEP CHAR(8)
);
GO

CREATE TABLE CLIENTES(
	CLIENTE_ID INT IDENTITY(1,1) PRIMARY KEY,
	CLIENTE_LOGIN VARCHAR(30),
	CLIENTE_SENHA VARCHAR(30),
	CLIENTE_NOME VARCHAR(60),
	EMAIL VARCHAR(30),
	DATA_ANIVERSARIO DATE,
	SEXO CHAR(1),
	FK_ENDERECO INT
);
GO

CREATE TABLE ORDEM(
	ORDEM_ID INT IDENTITY(1,1) PRIMARY KEY,
	ORDEM_DATE DATE,
	QUANTIDADE INT,
	VALOR_TOTAL MONEY,
	FK_CLIENTE_ORDEM INT,
	FK_JOGO_ORDEM INT
);
GO

CREATE TABLE PAGAMENTO(
	TRANSACAO_ID INT IDENTITY(1,1) PRIMARY KEY,
	FORMA_PAGAMENTO VARCHAR(30),
	DATA_PAGAMENTO DATE,
	FK_ORDEM INT
);
GO

CREATE TABLE AVALIACAO(
	AVALIACAO_ID INT IDENTITY(1,1) PRIMARY KEY,
	TEXTO_REVIEW VARCHAR(400),
	DATE_REVIEW DATE,
	FK_CLIENTE_AVALIACAO INT,
	FK_PRODUTO_AVALIACAO INT
)
GO;
