/*
INSERT INTO CLIENTES VALUES ('DANIEL BORBA', 'DANIEL@GMAIL.COM', '289954527')
GO

INSERT INTO CLIENTES( NOME, EMAIL, TELEFONE)
VALUES ('ELOISA', 'ELOISE@GMAIL.COM', '5198785254')
GO
INSERT INTO CLIENTES VALUES ('MANOEL GOMES', 'GM@GMAIL.COM', '42651382')
GO


INSERT INTO CLIENTES VALUES
( 'GABRIEL AMORIM', 'GABRIEL@GMAIL.COM', '268545742'),
( 'GABRIELA LINS', 'GABRIELA_LINS@GMAIL.COM', '289562172'),
( 'LUCIANA FERNANDA', 'LUCIANA_FERNANDA@GMAIL.COM', '272532475')
GO

------------------------------------------------

INSERT INTO PEDIDOS VALUES('2024-08-11', 115.00, 'TECLADO', 1)
GO

INSERT INTO PEDIDOS (DATA_PEDIDO, VALOR_TOTAL, PRODUTO, ID_CLIENTE)
VALUES 
('2024-05-02', 215.00, 'TECLADO', 2),
('2024-05-04', 185.00, 'FONE', 2),
('2024-05-11', 1750.00, 'MONITOR', 3),
('2024-05-15', 350.00, 'CPU', 4),
('2024-05-16', 360.00, 'CPU', 5),
('2024-05-16', 850.00, 'PROCESSADOR',5)
GO
*/




CREATE DATABASE PEDIDOS 
GO

USE PEDIDOS
GO

CREATE TABLE CLIENTES(
	ID_CLIENTE INT PRIMARY KEY  IDENTITY(1,1),
	NOME VARCHAR(60),
	EMAIL VARCHAR(60),
	TELEFONE VARCHAR(30)
)
GO



CREATE TABLE PEDIDOS(
	ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
	DATA_PEDIDO DATE,
	VALOR_TOTAL MONEY,
	PRODUTO VARCHAR(30),
	ID_CLIENTE INT
)
GO
-- ADICIONANDO FK A TABELA PEDIDOS
ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_CLIENTE_ID
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE) 
GO

-- SELECIONANDO QUEM COMPROU OS PRODUTOS
SELECT 
	C.NOME,
	C.TELEFONE,
	P.VALOR_TOTAL,
	P.PRODUTO,
	P.DATA_PEDIDO
FROM CLIENTES C
INNER JOIN PEDIDOS P
ON
C.ID_CLIENTE = P.ID_CLIENTE 
GO

-- SELECIONANDO QUAL CLIENTE GASTOU MAIS
SELECT 
	C.NOME,
	SUM(P.VALOR_TOTAL)AS TOTAL_COMPRAS
FROM CLIENTES C
INNER JOIN PEDIDOS P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.NOME
ORDER BY TOTAL_COMPRAS DESC
GO

-- LUCRO TOTAL DA EMPRESA
SELECT SUM(VALOR_TOTAL)AS LUCRO_TOTAL
FROM PEDIDOS 
GO

-- PRODUTO COMPRADO
SELECT PRODUTO, COUNT(PRODUTO)AS NUMERO_COMPRAS FROM PEDIDOS 
GROUP BY PRODUTO
ORDER BY NUMERO_COMPRAS DESC
GO

-- QUANTIDADE DE CLIENTES
SELECT COUNT(ID_CLIENTE) AS QUANTIDADE_CLIENTES FROM CLIENTES 
GO

SELECT COUNT(ID_CLIENTE) AS TOTAL_CLIENTES FROM CLIENTES
GO

-- CRIAÇÃO DE VIEWS 
CREATE VIEW QuantidadeTotalClientes AS
SELECT COUNT(ID_CLIENTE) AS QUANTIDADE_CLIENTES
FROM CLIENTES
GO



-- DEPOIS DE DAR UM INSERT MOSTRA A QUANTIDADE TOTAL DE CLIENTES
CREATE TRIGGER MostrarQuantidadeClientes
ON CLIENTES
AFTER INSERT
AS
BEGIN
  SELECT * FROM QuantidadeTotalClientes

END;
