
CREATE DATABASE PEDIDOS 
GO

USE PEDIDOS
GO

CREATE TABLE CLIENTES(
	ID_CLIENTE INT PRIMARY KEY  IDENTITY(1,1),
	NOME VARCHAR(60),
	EMAIL VARCHAR(60),
	TELEFONE VARCHAR(30)
)
GO

INSERT INTO CLIENTES VALUES ('DANIEL BORBA', 'DANIEL@GMAIL.COM', '289954527')
GO

CREATE TABLE PEDIDOS(
	ID_PEDIDO INT PRIMARY KEY IDENTITY(1,1),
	DATA_PEDIDO DATE,
	VALOR_TOTAL MONEY,
	PRODUTO VARCHAR(30),
	ID_CLIENTE INT
)
GO

INSERT INTO PEDIDOS VALUES('2024-08-11', 115.00, 'TECLADO', 1)
GO

-- ADICIONANDO FK A TABELA PEDIDOS
ALTER TABLE PEDIDOS
ADD CONSTRAINT FK_CLIENTE_ID
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE) 
GO

