-- CRIAÇÃO DE VIEWS 
CREATE VIEW QuantidadeTotalClientes AS
SELECT COUNT(ID_CLIENTE) AS QUANTIDADE_CLIENTES
FROM CLIENTES
GO

SELECT * FROM QuantidadeTotalClientes
GO


-- DEPOIS DE DAR UM INSERT MOSTRA A QUANTIDADE TOTAL DE CLIENTES
CREATE TRIGGER MostrarQuantidadeClientes
ON CLIENTES
AFTER INSERT
AS
BEGIN
  SELECT * FROM QuantidadeTotalClientes
END;
