-- SELECIONANDO QUEM COMPROU OS PRODUTOS
SELECT 
	C.NOME,
	C.TELEFONE,
	P.VALOR_TOTAL,
	P.PRODUTO,
	P.DATA_PEDIDO
FROM CLIENTES C
INNER JOIN PEDIDOS P
ON
C.ID_CLIENTE = P.ID_CLIENTE 
GO

-- SELECIONANDO QUAL CLIENTE GASTOU MAIS
SELECT 
	C.NOME,
	SUM(P.VALOR_TOTAL)AS TOTAL_COMPRAS
FROM CLIENTES C
INNER JOIN PEDIDOS P ON C.ID_CLIENTE = P.ID_CLIENTE
GROUP BY C.NOME
ORDER BY TOTAL_COMPRAS DESC
GO

-- LUCRO TOTAL DA EMPRESA
SELECT SUM(VALOR_TOTAL)AS LUCRO_TOTAL
FROM PEDIDOS 
GO

-- PRODUTO COMPRADO
SELECT PRODUTO, COUNT(PRODUTO)AS NUMERO_COMPRAS FROM PEDIDOS 
GROUP BY PRODUTO
ORDER BY NUMERO_COMPRAS DESC
GO

-- QUANTIDADE DE CLIENTES
SELECT COUNT(ID_CLIENTE) AS QUANTIDADE_CLIENTES FROM CLIENTES 
GO


SELECT COUNT(ID_CLIENTE) AS TOTAL_CLIENTES FROM CLIENTES
GO
