CREATE DATABASE MINILOJA;

USE MINILOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	PRECO FLOAT(10,2),
	IDVENDEDOR INT
);


CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);


ALTER TABLE PRODUTO ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY(IDVENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR);


/* CREATE BACKUP */
CREATE TABLE BKP_VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

CREATE TABLE BKP_PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	PRECO FLOAT(10,2),
	IDVENDEDOR INT
);
