-- Criação do banco normal

CREATE DATABASE MINILOJA;

USE MINILOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	PRECO FLOAT(10,2),
	IDVENDEDOR INT
);

CREATE TABLE VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

ALTER TABLE PRODUTO ADD CONSTRAINT FK_VENDEDOR
FOREIGN KEY(IDVENDEDOR) REFERENCES VENDEDOR(IDVENDEDOR);


-- Criação do banco de backup
CREATE DATABASE BKP_LOJA;

USE BKP_LOJA;

CREATE TABLE BKP_PRODUTO(
	IDBAKCUP INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(30),
    PRECO FLOAT(10,2),
    IDVENDEDOR INT,
    PRECO_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	IDVENDEDOR_ALTEROU INT
);

CREATE TABLE BKP_VENDEDOR(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

ALTER TABLE BKP_PRODUTO ADD CONSTRAINT FK_BKP_VENDEDOR
FOREIGN KEY(IDVENDEDOR) REFERENCES BKP_VENDEDOR(IDVENDEDOR);
