INSERT INTO VENDEDOR VALUES(NULL, "DANIEL BORBA");
INSERT INTO PRODUTO VALUES(NULL, "CARREGADOR 5W", 220, 1);

-- UPDATE PARA TESTAR A QUERY
UPDATE PRODUTO SET PRECO = 100, NOME = "CARREGADOR 5W", IDVENDEDOR =2 
WHERE IDPRODUTO = 4;
