-- UTILIZANDO PROCEDURE PARA O SELECT COTIDIANO NO BKP PARA VERIFICAR QUEM MODIFICOU OS PREÇOS
DELIMITER //
CREATE PROCEDURE BUSCA_ALTERACAO()
BEGIN
    SELECT P.NOME AS NOME_PRODUTO, 
           P.PRECO AS PRECO_ANTIGO, 
           P.PRECO_ALTERADO, 
           V.NOME AS QUEM_ALTEROU, 
           P.DATA
    FROM BKP_PRODUTO P
    INNER JOIN BKP_VENDEDOR V ON P.IDVENDEDOR_ALTEROU = V.IDVENDEDOR;
END //

DELIMITER ;


CALL BUSCA_ALTERACAO()
