/* MOSTRA QUEM FOI QUE ALTEROU O PREÇO DO PRODUTO*/

-- no banco bkp para saber quem alterou o preco do produto.
SELECT P.NOME AS NOME_PRODUTO, P.PRECO AS PRECO_ANTIGO, P.PRECO_ALTERADO, V.NOME AS QUEM_ALATEROU, P.DATA
FROM BKP_PRODUTO P
INNER JOIN BKP_VENDEDOR V
ON P.IDVENDEDOR_ALTEROU = V.IDVENDEDOR;
