
/* PARA CADA INSERT DE UM VENDEDOR NO BANCO PRINCIPAL, TAMBÉM DA UM INSERT NO BANCO DE BKP */
CREATE TRIGGER AUDIT_VENDEDORES
AFTER INSERT ON VENDEDOR
FOR EACH ROW
BEGIN 
	INSERT INTO BACKUP_MINILOJA.BKP_VENDEDOR VALUES(NULL, NEW.NOME);
END
$


/* QUANDO UM PRODUTO FOR CADASTRADO IR DIRETO PARA O BANCO BACKUP */
CREATE TRIGGER SAVE_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW 
BEGIN	
	INSERT BKP_LOJA.BKP_PRODUTO VALUES(OLD.IDPRODUTO, OLD.NOME, OLD.PRECO, OLD.IDVENDEDOR, NEW.PRECO, NOW(), NEW.IDVENDEDOR);
END 
$
