/* Banco simples criado com dados ficticios para executar algumas querys,
afim de estudo, o banco contém apenas uma tabela e logo algumas querys
o nome do banco é about pois a intenção é criar querys para saber sobre os dados
dos funcionarios de uma empresa, OS DADOS SERÃO INSERIDOS VIA CSV COM FERRAMENTAS ETL*/

CREATE DATABASE ABOUT;
GO

CREATE TABLE FUNCIONARIO(
 ID_FUNCIONARIO INT NOT NULL,
 NOME VARCHAR(50) NOT NULL,
 SOBRENOME VARCHAR(50) NOT NULL,
 EMAIL VARCHAR(50),
 SEXO CHAR(1),
 SALARIO MONEY,
 FUNCAO VARCHAR(50)
)
GO

USE ABOUT
GO

/* QUERYS */
 
-- O NOME DA PESSOA, SEXO, FUNCAO ONDE O SALARIO É MAIOR DE 4MIL, DO MAIOR PARA O MENOR.
SELECT NOME, SEXO, FUNCAO, SALARIO
FROM FUNCIONARIO
WHERE SALARIO > 4000
ORDER BY SALARIO DESC
GO

-- ID, NOME DAS PESSOAS QUE ESTÃO COM O EMAIL NULO PARA ENVIARMOS UMA NOTIFICAÇÃO INSTRUINDO A CADASTRAR.
SELECT ID_FUNCIONARIO, NOME, EMAIL AS EMAIL_VAZIO
FROM FUNCIONARIO
WHERE EMAIL IS NULL OR EMAIL = ''
GO

--CONTAGEM DE EMAIL DE PESSOAS QUE NÃO POSSUEM EMAIL CADASTRADOS
SELECT COUNT(*) AS total_funcionarios_sem_email
FROM FUNCIONARIO	
WHERE EMAIL IS NULL OR EMAIL = ''
GO
--

-- ID, NOME, SALARIO, PROFISSAO DO HOMEM QUE MAIS GANHA
SELECT ID_FUNCIONARIO AS ID, NOME, FUNCAO, SEXO,(SALARIO)
FROM FUNCIONARIO 
WHERE SEXO = 'M'
AND SALARIO = (SELECT MAX(SALARIO) FROM FUNCIONARIO WHERE SEXO = 'M');
GO
GO
-- RETURN = VERNON, ESPECIALISTA EM CONTROLE DE QUALITADE , SALARIO = $ 19982,81


-- ID, NOME, SALARIO, PROFISSAO DO MULHER QUE MAIS GANHA
SELECT ID_FUNCIONARIO AS ID, NOME, FUNCAO, SEXO,(SALARIO)
FROM FUNCIONARIO 
WHERE SEXO = 'F'
AND SALARIO = (SELECT MAX(SALARIO) FROM FUNCIONARIO WHERE SEXO = 'F');
GO
-- RETURN = KAT, ASSISTENTE DE PESQUISA, SALARIO = $ 19957,81

/* FUNÇÕES QUE POSSUI MAIS FUNCIONARIOS EM ORDEM DECRESCENTE */
SELECT FUNCAO ,COUNT(*) AS QUANTIDADE_FUNCIONARIOS
FROM FUNCIONARIO
GROUP BY FUNCAO 
ORDER BY QUANTIDADE_FUNCIONARIOS DESC
GO

/* A FUNÇÃO QUE POSSUI MAIS FUNCIONARIO*/
SELECT TOP 1 FUNCAO, COUNT(*) AS QUANTIDADE_FUNCIONARIOS
FROM FUNCIONARIO
GROUP BY FUNCAO
ORDER BY QUANTIDADE_FUNCIONARIOS DESC;
