CREATE DATABASE INVESTIMENTOS
GO

USE INVESTIMENTOS
GO

CREATE TABLE FIIS(
	ID_COMPRA INT IDENTITY(1,1) PRIMARY KEY,
	ATIVO VARCHAR(10),
	COTACAO DECIMAL (10,2),
	QTD_COMPRADA INT,
	VALOR_TOTAL DECIMAL,
	DATA_DE_COMPRA DATE
)
GO

SELECT * FROM FIIS 
GO

--MOSTRANDO O VALOR TOTAL INVESTIDO 

SELECT SUM(VALOR_TOTAL)AS VALOR_TOTAL_INVESTIDO FROM FIIS
GO

-- COMO SABER O VALOR DE PERDA OU LUCRO POR ALTERAÇÃO DE PREÇO DO ATIVO

/* ETAPA 01 - PEGAR O VALOR DA COTACAO ATUAL DIMINUIR PELA COTAÇÃO 
QUE PAGUEI E DEPOIS MULTIPLICAR PELA QUANTIDADE COMPRADA,
HOJE 17/06/2024 - O VGIR11 ESTÁ CUSTANDO R$ 9,77
*/
SELECT (COTACAO - 9.77) * QTD_COMPRADA AS PERDA_TOTAL
FROM FIIS
WHERE ID_COMPRA = 1
GO

-- CRIANDO UMA PROCEDURE PARA AUTOMATIZAR E SIMPLIFICAR ESSE SELECT

CREATE PROCEDURE CalcularPerdaTotal 
	@ID_COMPRA INT
AS
BEGIN
	SELECT (COTACAO - 9.77) * QTD_COMPRADA AS PERDA_TOTAL
	FROM FIIS
	WHERE ID_COMPRA = @ID_COMPRA
END;
GO
EXEC CalcularPerdaTotal @ID_COMPRA = 1;
/* OBS SÓ FUNCIONA SE FOR USADA DIARIAMENTE POIS OS VALORES MUDAM E O PAPEL TAMBÉM. É SÓ UMA BASE PARA MAIS PARA FRENTE CONSUMIR A COTACAO ATUAL DE UMA API EXTERNA! */
