
/* CRIANDO TRIGGER
- TODA VEZ QUE UMA VENDA FOR INSERIDA, FAZ O CALCULO AUTOMATICO DO VALOR TOTAL
*/
CREATE TRIGGER TRG_CALCULAR_VALORTOTAL
ON vendas
AFTER INSERT, UPDATE
AS
BEGIN
    UPDATE vendas
    SET valorTotal = i.quantidadeProduto * e.precoProduto
    FROM vendas v
    INNER JOIN inserted i ON v.idvendas = i.idvendas
    INNER JOIN estoque e ON i.idproduto = e.idproduto;
END
go

/* CRIANDO TRIGGER
- TODA VEZ QUE UMA VENDA FOR EXECUTADA DIMINUI A QUANTIDADE DE PRODUTO NO ESTOQUE
*/

CREATE TRIGGER TRG_VENDA_ATUALIZA_ESTOQUE
ON VENDAS
AFTER INSERT 
AS BEGIN 
	-- ATUALIZAR O ESTOQUE
	UPDATE ESTOQUE
	SET quantidadeProduto = estoque.quantidadeProduto - i.quantidadeProduto
	FROM ESTOQUE
	INNER JOIN INSERTED I ON ESTOQUE.IDPRODUTO = I.idCliente;
END;
GO
