CREATE DATABASE ESCOLA
GO

USE ESCOLA
GO

CREATE TABLE ALUNOS (
	ID_ALUNO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	SOBRENOME VARCHAR(50),
	DATA_NASCIMENTO DATE
)
GO

CREATE TABLE CURSOS (
	ID_CURSO INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(40),
	DESCRICAO TEXT
)
GO

CREATE TABLE INSCRICOES(
	ID_INSCRICAO INT IDENTITY(1,1) PRIMARY KEY,
	ID_ALUNO INT,
	ID_CURSO INT,
	DATA_INSCRICAO DATE
)
GO

ALTER TABLE INSCRICOES 
ADD CONSTRAINT FK_ID_ALUNO FOREIGN KEY(ID_ALUNO)
REFERENCES ALUNOS(ID_ALUNO)
GO

ALTER TABLE CURSOS
ADD CONSTRAINT FK_ID_CURSO FOREIGN KEY(ID_CURSO)
REFERENCES CURSOS(ID_CURSO)
GO

CREATE TABLE PROFESSORES(
	ID_PROFESSOR INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(30),
	SOBRENOME VARCHAR(50),
	ESPECIALIDADE VARCHAR(50)

)
GO

CREATE TABLE AULAS (
	ID_AULA INT PRIMARY KEY,
	ID_CURSO INT,
	ID_PROFESSOR INT,
	DATA_AULA DATE
)
GO

ALTER TABLE AULAS
ADD CONSTRAINT FK_ID_CURSO_AULAS FOREIGN KEY(ID_CURSO)
REFERENCES CURSOS(ID_CURSO)
GO

ALTER TABLE AULAS
ADD CONSTRAINT FK_ID_PROFESSOR FOREIGN KEY(ID_PROFESSOR)
REFERENCES PROFESSORES(ID_PROFESSOR)
GO
