/* CREATE */

CREATE DATABASE VETERINARIA

USE VETERINARIA
GO

CREATE TABLE PACIENTE(
	PACIENTEID INT IDENTITY(1,1),
	NOME VARCHAR(60),
	ESPECIE VARCHAR(60),
	RAÇA VARCHAR(60),
	DATA_NASCIMENTO DATE,
	DONOID INT
)
GO

CREATE TABLE VETERINARIOS(
	VETERINARIOID INT IDENTITY(1,1),
	NOME_VETERINARIO VARCHAR(40),
	ESPECIALIDADE VARCHAR(30),
	DATA_CONTRATACAO DATE
)
GO

CREATE TABLE CONSULTAS(
	CONSULTAID INT IDENTITY(1,1),
	DATA_CONSULTA DATE,
	MOTIVO TEXT,
	PACIENTEID INT,
	VETERINARIOID INT
)
GO


CREATE TABLE DONO(
	DONOID INT IDENTITY(1,1),
	NOME VARCHAR(40),
	TELEFONE VARCHAR(18),
	EMAIL VARCHAR(50)
)
GO
