/* CREATE */

CREATE DATABASE VETERINARIA

USE VETERINARIA
GO

CREATE TABLE PACIENTE(
	PACIENTEID INT IDENTITY(1,1),
	NOME VARCHAR(60),
	ESPECIE VARCHAR(60),
	RAÇA VARCHAR(60),
	DATA_NASCIMENTO DATE,
	DONOID INT,
	PRIMARY KEY (PACIENTEID)
)
GO

ALTER TABLE PACIENTE
ADD CONSTRAINT FK_DONOID
FOREIGN KEY(DONOID) REFERENCES DONO(DONOID)
GO

CREATE TABLE VETERINARIOS(
	VETERINARIOID INT IDENTITY(1,1),
	NOME_VETERINARIO VARCHAR(40),
	ESPECIALIDADE VARCHAR(30),
	DATA_CONTRATACAO DATE,
	PRIMARY KEY (VETERINARIOID)
)
GO

CREATE TABLE CONSULTAS(
	CONSULTAID INT IDENTITY(1,1),
	DATA_CONSULTA DATE,
	MOTIVO TEXT,
	PACIENTEID INT,
	VETERINARIOID INT
	PRIMARY KEY(CONSULTAID)
)
GO
ALTER TABLE CONSULTAS
ADD CONSTRAINT FK_VETERINARIOID
FOREIGN KEY(VETERINARIOID) REFERENCES VETERINARIOS(VETERINARIOID)
GO

CREATE TABLE DONO(
	DONOID INT IDENTITY(1,1),
	NOME VARCHAR(40),
	TELEFONE VARCHAR(18),
	EMAIL VARCHAR(50),
	PRIMARY KEY (DONOID) 
)
GO

