-- QUERY PARA LISTAR TODAS CONSULTAS REALIZADAS ( NOME DO PACIENTE, ESPECIE, DATA DA COSNULTA, MOTIVO E NOME DO VETERINÁRIO
SELECT 
	P.NOME, P.ESPECIE, C.DATA_CONSULTA, C.MOTIVO, V.NOME_VETERINARIO
FROM 
	PACIENTE AS P
INNER JOIN
	CONSULTAS AS C
ON P.PACIENTEID = C.PACIENTEID
INNER JOIN
	VETERINARIOS AS V
ON C.VETERINARIOID = V.VETERINARIOID
GO
-------------------------------------------------------------------------------

-- TODOS OS PACIENTES QUE FORAM ATENDIDOS POR UM VETERINÁRIO ESPECÍFICO E A DATA DA CONSULTA
SELECT 
	P.NOME, P.ESPECIE, C.DATA_CONSULTA, V.NOME_VETERINARIO
FROM 
	PACIENTE AS P
INNER JOIN
	CONSULTAS AS C
ON P.PACIENTEID = C.PACIENTEID
INNER JOIN
	VETERINARIOS AS V
ON C.VETERINARIOID = V.VETERINARIOID
WHERE V.NOME_VETERINARIO = 'MARIO LOPES'
--------------------------------------------------------

-- LISTAR NOME DE TODOS OS DONOS DE ANIMAIS E NOME DOS SEUS RESPECTIVOS ANIMAIS CADASTRADOS.

SELECT P.NOME, D.NOME
FROM
	PACIENTE AS P
INNER JOIN 
	DONO AS D
ON P.DONOID = D.DONOID

