-- QUERY PARA LISTAR TODAS CONSULTAS REALIZADAS ( NOME DO PACIENTE, ESPECIE, DATA DA COSNULTA, MOTIVO E NOME DO VETERINÁRIO
SELECT 
	P.NOME, P.ESPECIE, C.DATA_CONSULTA, C.MOTIVO, V.NOME_VETERINARIO
FROM 
	PACIENTE AS P
INNER JOIN
	CONSULTAS AS C
ON P.PACIENTEID = C.PACIENTEID
INNER JOIN
	VETERINARIOS AS V
ON C.VETERINARIOID = V.VETERINARIOID
GO
-------------------------------------------------------------------------------
