
CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
    IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT
);

INSERT INTO VENDEDORES VALUES(NULL, 'MAFRA', 12121,454545,78797);

INSERT INTO VENDEDORES VALUES(NULL, 'DAN', 8971,4878545,78887);

INSERT INTO VENDEDORES VALUES(NULL, 'JOAO', 665658,545878,59978);

INSERT INTO VENDEDORES VALUES(NULL, 'LILIANE', 8798789,787878,78785);

SELECT NOME, (JAN + FEV + MAR) AS TOTAL, (JAN + FEV + MAR)/3  AS MEDIA FROM VENDEDORES;
/*  CONSOME MUITO DO BANCO.*/

CREATE TABLE VEND_TOTAL(
    NOME VARCHAR(50),
    JAN INT,
    FEV INT,
    MAR INT,
    TOTAL INT,
    MEDIA INT
);

DELIMITER $

CREATE PROCEDURE INSEREDADOS()
BEGIN
    DECLARE FIM INT DEFAULT 0;
    DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
    DECLARE VNOME VARCHAR(50);

    DECLARE REG CURSOR FOR (
        SELECT NOME, JAN, FEV, MAR FROM VENDEDORES
    );

    DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;

    OPEN REG;

    REPEAT
        FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
        IF NOT FIM THEN
            SET VTOTAL = VAR1 + VAR2 + VAR3;
            SET VMEDIA = VTOTAL / 3;

            INSERT INTO VEND_TOTAL VALUES (VNOME, VAR1, VAR2, VAR3, VTOTAL, VMEDIA);
        END IF;
    UNTIL FIM END REPEAT;

    CLOSE REG;
END;
$

Call INSEREDADOS();

select * from VEND_TOTAL;
