CREATE TABLE AUTORES (
	IDAUTORES INT PRIMARY KEY NOT NULL,
	NOMEAUTOR VARCHAR(60) NOT NULL,
	NACIONALIDADE VARCHAR(15) NOT NULL,
	DATANASCIMENTO DATE NOT NULL,
	DATAFALECIMENTO DATE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY NOT NULL,
	RUA VARCHAR(50),
	CIDADE VARCHAR(40),
	CEP VARCHAR(8),
	UF CHAR(2)
);

CREATE TABLE MEMBROS (
	IDMEMBROS INT PRIMARY KEY NOT NULL,
	NOMEMEMBRO VARCHAR(50),
	TELMEMBRO VARCHAR(20),
	DATAREGISTRO DATE,
	IDENDERECO INT FOREIGN KEY,
	FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO(IDENDERECO)
);

CREATE TABLE LIVROS (
	ISBN INT PRIMARY KEY NOT NULL,
	TITULO VARCHAR(80),
	ANOPUBLICACAO DATE,
	GENEROLIVRO VARCHAR(20),
	EDITORA VARCHAR(45),
	QTDDISPONIVEL INT,
	AUTOR VARCHAR(45),
	IDAUTORES INT FOREIGN KEY
	FOREIGN KEY(IDAUTORES) REFERENCES AUTORES(IDAUTORES)
);

CREATE TABLE RESERVAS (
	IDRESERVAS INT PRIMARY KEY NOT NULL,
	DATARESERVA DATE,
	STATUS BOOLEAN,
	ISBN INT,
	IDMEMBROS INT ,
	FOREIGN KEY(ISBN) REFERENCES LIVROS(ISBN),
	FOREIGN KEY (IDMEMBROS) REFERENCES MEMBROS(IDMEMBROS)
);

CREATE TABLE EMPRESTIMOS (
	IDEMPRESTIMOS INT PRIMARY KEY NOT NULL,
	DATAEMPRESTIMO DATE,
	DATADEVOLUCAO DATE,
	ISBN INT ,
	IDMEMBROS INT ,
	FOREIGN KEY(ISBN) REFERENCES LIVROS(ISBN),
	FOREIGN KEY(IDMEMBROS) REFERENCES MEMBROS(IDMEMBROS)
);
